kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: px-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "2"
  priority_io: "high"
  group: "cassandra_vg"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: px-sc-shared
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
  priority_io: "high"
  shared: "true"
